# configurations-eks/apis/xrd.yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.segoja7.example
spec:
  group: segoja7.example
  names:
    kind: XCLUSTER
    plural: xclusters
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
                description: "ID único para este cluster y sus recursos."
              region:
                type: string
                description: "Región de AWS para el cluster."
              providerConfigName:
                type: string
                description: "Nombre del ProviderConfig a usar."
                default: "default"
              tags:
                type: object
                description: A map of tags to apply to all resources.
                additionalProperties:
                  type: string
              encryptCluster:
                type: boolean
                description: A boolean flag to enable/disable kms encrypt in eks cluster
                default: false
              accountId: 
                type: string
                description: Accountid of the account
              authenticationMode:
                type: string
                description: "Authentication mode for the EKS cluster. Valid values are 'API,' 'CONFIG_MAP' and 'API_AND_CONFIG_MAP'."
                default: "API_AND_CONFIG_MAP"
              logging:
                type: array
                description: "List of log types to enable for the cluster. Valid values are 'api', 'audit', 'authenticator', 'controllerManager', and 'scheduler'."
                items:
                  type: string
              endpointPublicAccess:
                type: boolean
                description: "Enable public access to API server endpoint"
                default: true
              endpointPrivateAccess:
                type: boolean
                description: "Enable private access to API server endpoint."
                default: true
              publicAccessCidrs:
                type: array
                description: "List of CIDR blocks to allow access to the public API server endpoint."
                default: ["0.0.0.0/0"]
              networkId:
                type: string
                description: "ID of the network where the cluster will be deployed."
              clusterVersion:
                type: string
                description: "Kubernetes version for the cluster."
            required: ["id", "region", "accountId", "networkId"]
