apiVersion: opentofu.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  # This is the default ProviderConfig that Workspaces will use if they
  # don't specify a providerConfigRef.
  name: default
spec:
  configuration: |
    terraform {
      backend "kubernetes" {
        secret_suffix     = "providerconfig-default"
        namespace         = "crossplane-system"
        in_cluster_config = true
      }
    }
    # We configure the provider to use the mounted credentials.
    # We don't specify the provider source or version here, as that is the
    # responsibility of the remote Terraform module.
    provider "aws" {
      region                   = "us-east-1"
      shared_credentials_files = ["${path.module}/aws-creds.ini"]
    }
  credentials:
    - filename: aws-creds.ini
      secretRef:
        key: creds
        name: aws-secrets
        namespace: crossplane-system
      source: Secret
